//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.12 at 11:59:10 AM PDT 
//


package pnnl.goss.powergrid.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Bus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BusNumber">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PowergridId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SubstationId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BusName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BaseKv">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Code">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Pl">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Ql">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Gl">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Bl">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AreaId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Va">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Vm">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ZoneId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Mrid">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="36"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bus", propOrder = {
    "busNumber",
    "powergridId",
    "substationId",
    "busName",
    "baseKv",
    "code",
    "pl",
    "ql",
    "gl",
    "bl",
    "areaId",
    "va",
    "vm",
    "zoneId",
    "mrid"
})
public class Bus
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "BusNumber")
    protected int busNumber;
    @XmlElement(name = "PowergridId")
    protected int powergridId;
    @XmlElement(name = "SubstationId")
    protected Integer substationId;
    @XmlElement(name = "BusName", required = true)
    protected String busName;
    @XmlElement(name = "BaseKv")
    protected double baseKv;
    @XmlElement(name = "Code")
    protected int code;
    @XmlElement(name = "Pl")
    protected double pl;
    @XmlElement(name = "Ql")
    protected double ql;
    @XmlElement(name = "Gl")
    protected double gl;
    @XmlElement(name = "Bl")
    protected double bl;
    @XmlElement(name = "AreaId")
    protected int areaId;
    @XmlElement(name = "Va")
    protected double va;
    @XmlElement(name = "Vm")
    protected double vm;
    @XmlElement(name = "ZoneId")
    protected int zoneId;
    @XmlElement(name = "Mrid", required = true)
    protected String mrid;

    /**
     * Gets the value of the busNumber property.
     * 
     */
    public int getBusNumber() {
        return busNumber;
    }

    /**
     * Sets the value of the busNumber property.
     * 
     */
    public void setBusNumber(int value) {
        this.busNumber = value;
    }

    public boolean isSetBusNumber() {
        return true;
    }

    /**
     * Gets the value of the powergridId property.
     * 
     */
    public int getPowergridId() {
        return powergridId;
    }

    /**
     * Sets the value of the powergridId property.
     * 
     */
    public void setPowergridId(int value) {
        this.powergridId = value;
    }

    public boolean isSetPowergridId() {
        return true;
    }

    /**
     * Gets the value of the substationId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSubstationId() {
        return substationId;
    }

    /**
     * Sets the value of the substationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSubstationId(Integer value) {
        this.substationId = value;
    }

    public boolean isSetSubstationId() {
        return (this.substationId!= null);
    }

    /**
     * Gets the value of the busName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusName() {
        return busName;
    }

    /**
     * Sets the value of the busName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusName(String value) {
        this.busName = value;
    }

    public boolean isSetBusName() {
        return (this.busName!= null);
    }

    /**
     * Gets the value of the baseKv property.
     * 
     */
    public double getBaseKv() {
        return baseKv;
    }

    /**
     * Sets the value of the baseKv property.
     * 
     */
    public void setBaseKv(double value) {
        this.baseKv = value;
    }

    public boolean isSetBaseKv() {
        return true;
    }

    /**
     * Gets the value of the code property.
     * 
     */
    public int getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     */
    public void setCode(int value) {
        this.code = value;
    }

    public boolean isSetCode() {
        return true;
    }

    /**
     * Gets the value of the pl property.
     * 
     */
    public double getPl() {
        return pl;
    }

    /**
     * Sets the value of the pl property.
     * 
     */
    public void setPl(double value) {
        this.pl = value;
    }

    public boolean isSetPl() {
        return true;
    }

    /**
     * Gets the value of the ql property.
     * 
     */
    public double getQl() {
        return ql;
    }

    /**
     * Sets the value of the ql property.
     * 
     */
    public void setQl(double value) {
        this.ql = value;
    }

    public boolean isSetQl() {
        return true;
    }

    /**
     * Gets the value of the gl property.
     * 
     */
    public double getGl() {
        return gl;
    }

    /**
     * Sets the value of the gl property.
     * 
     */
    public void setGl(double value) {
        this.gl = value;
    }

    public boolean isSetGl() {
        return true;
    }

    /**
     * Gets the value of the bl property.
     * 
     */
    public double getBl() {
        return bl;
    }

    /**
     * Sets the value of the bl property.
     * 
     */
    public void setBl(double value) {
        this.bl = value;
    }

    public boolean isSetBl() {
        return true;
    }

    /**
     * Gets the value of the areaId property.
     * 
     */
    public int getAreaId() {
        return areaId;
    }

    /**
     * Sets the value of the areaId property.
     * 
     */
    public void setAreaId(int value) {
        this.areaId = value;
    }

    public boolean isSetAreaId() {
        return true;
    }

    /**
     * Gets the value of the va property.
     * 
     */
    public double getVa() {
        return va;
    }

    /**
     * Sets the value of the va property.
     * 
     */
    public void setVa(double value) {
        this.va = value;
    }

    public boolean isSetVa() {
        return true;
    }

    /**
     * Gets the value of the vm property.
     * 
     */
    public double getVm() {
        return vm;
    }

    /**
     * Sets the value of the vm property.
     * 
     */
    public void setVm(double value) {
        this.vm = value;
    }

    public boolean isSetVm() {
        return true;
    }

    /**
     * Gets the value of the zoneId property.
     * 
     */
    public int getZoneId() {
        return zoneId;
    }

    /**
     * Sets the value of the zoneId property.
     * 
     */
    public void setZoneId(int value) {
        this.zoneId = value;
    }

    public boolean isSetZoneId() {
        return true;
    }

    /**
     * Gets the value of the mrid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMrid() {
        return mrid;
    }

    /**
     * Sets the value of the mrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMrid(String value) {
        this.mrid = value;
    }

    public boolean isSetMrid() {
        return (this.mrid!= null);
    }

}
