//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.12 at 11:59:10 AM PDT 
//


package pnnl.goss.powergrid.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Machine complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Machine">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MachineId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PowergridId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BusNumber">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MachineName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Pgen">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Qgen">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MaxPgen">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MaxQgen">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MinPgen">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MinQgen">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Status">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IsSvc">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Vs">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Ireg">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Zr">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Zx">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Rt">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Xt">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Gtap">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RmPct">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Mrid">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="36"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Machine", propOrder = {
    "machineId",
    "powergridId",
    "busNumber",
    "machineName",
    "pgen",
    "qgen",
    "maxPgen",
    "maxQgen",
    "minPgen",
    "minQgen",
    "status",
    "isSvc",
    "vs",
    "ireg",
    "zr",
    "zx",
    "rt",
    "xt",
    "gtap",
    "rmPct",
    "mrid"
})
public class Machine
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "MachineId")
    protected int machineId;
    @XmlElement(name = "PowergridId")
    protected int powergridId;
    @XmlElement(name = "BusNumber")
    protected int busNumber;
    @XmlElement(name = "MachineName", required = true)
    protected String machineName;
    @XmlElement(name = "Pgen")
    protected double pgen;
    @XmlElement(name = "Qgen")
    protected double qgen;
    @XmlElement(name = "MaxPgen")
    protected double maxPgen;
    @XmlElement(name = "MaxQgen")
    protected double maxQgen;
    @XmlElement(name = "MinPgen")
    protected double minPgen;
    @XmlElement(name = "MinQgen")
    protected double minQgen;
    @XmlElement(name = "Status")
    protected int status;
    @XmlElement(name = "IsSvc")
    protected int isSvc;
    @XmlElement(name = "Vs")
    protected double vs;
    @XmlElement(name = "Ireg")
    protected int ireg;
    @XmlElement(name = "Zr")
    protected double zr;
    @XmlElement(name = "Zx")
    protected double zx;
    @XmlElement(name = "Rt")
    protected double rt;
    @XmlElement(name = "Xt")
    protected double xt;
    @XmlElement(name = "Gtap")
    protected double gtap;
    @XmlElement(name = "RmPct")
    protected double rmPct;
    @XmlElement(name = "Mrid", required = true)
    protected String mrid;

    /**
     * Gets the value of the machineId property.
     * 
     */
    public int getMachineId() {
        return machineId;
    }

    /**
     * Sets the value of the machineId property.
     * 
     */
    public void setMachineId(int value) {
        this.machineId = value;
    }

    public boolean isSetMachineId() {
        return true;
    }

    /**
     * Gets the value of the powergridId property.
     * 
     */
    public int getPowergridId() {
        return powergridId;
    }

    /**
     * Sets the value of the powergridId property.
     * 
     */
    public void setPowergridId(int value) {
        this.powergridId = value;
    }

    public boolean isSetPowergridId() {
        return true;
    }

    /**
     * Gets the value of the busNumber property.
     * 
     */
    public int getBusNumber() {
        return busNumber;
    }

    /**
     * Sets the value of the busNumber property.
     * 
     */
    public void setBusNumber(int value) {
        this.busNumber = value;
    }

    public boolean isSetBusNumber() {
        return true;
    }

    /**
     * Gets the value of the machineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMachineName() {
        return machineName;
    }

    /**
     * Sets the value of the machineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMachineName(String value) {
        this.machineName = value;
    }

    public boolean isSetMachineName() {
        return (this.machineName!= null);
    }

    /**
     * Gets the value of the pgen property.
     * 
     */
    public double getPgen() {
        return pgen;
    }

    /**
     * Sets the value of the pgen property.
     * 
     */
    public void setPgen(double value) {
        this.pgen = value;
    }

    public boolean isSetPgen() {
        return true;
    }

    /**
     * Gets the value of the qgen property.
     * 
     */
    public double getQgen() {
        return qgen;
    }

    /**
     * Sets the value of the qgen property.
     * 
     */
    public void setQgen(double value) {
        this.qgen = value;
    }

    public boolean isSetQgen() {
        return true;
    }

    /**
     * Gets the value of the maxPgen property.
     * 
     */
    public double getMaxPgen() {
        return maxPgen;
    }

    /**
     * Sets the value of the maxPgen property.
     * 
     */
    public void setMaxPgen(double value) {
        this.maxPgen = value;
    }

    public boolean isSetMaxPgen() {
        return true;
    }

    /**
     * Gets the value of the maxQgen property.
     * 
     */
    public double getMaxQgen() {
        return maxQgen;
    }

    /**
     * Sets the value of the maxQgen property.
     * 
     */
    public void setMaxQgen(double value) {
        this.maxQgen = value;
    }

    public boolean isSetMaxQgen() {
        return true;
    }

    /**
     * Gets the value of the minPgen property.
     * 
     */
    public double getMinPgen() {
        return minPgen;
    }

    /**
     * Sets the value of the minPgen property.
     * 
     */
    public void setMinPgen(double value) {
        this.minPgen = value;
    }

    public boolean isSetMinPgen() {
        return true;
    }

    /**
     * Gets the value of the minQgen property.
     * 
     */
    public double getMinQgen() {
        return minQgen;
    }

    /**
     * Sets the value of the minQgen property.
     * 
     */
    public void setMinQgen(double value) {
        this.minQgen = value;
    }

    public boolean isSetMinQgen() {
        return true;
    }

    /**
     * Gets the value of the status property.
     * 
     */
    public int getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     */
    public void setStatus(int value) {
        this.status = value;
    }

    public boolean isSetStatus() {
        return true;
    }

    /**
     * Gets the value of the isSvc property.
     * 
     */
    public int getIsSvc() {
        return isSvc;
    }

    /**
     * Sets the value of the isSvc property.
     * 
     */
    public void setIsSvc(int value) {
        this.isSvc = value;
    }

    public boolean isSetIsSvc() {
        return true;
    }

    /**
     * Gets the value of the vs property.
     * 
     */
    public double getVs() {
        return vs;
    }

    /**
     * Sets the value of the vs property.
     * 
     */
    public void setVs(double value) {
        this.vs = value;
    }

    public boolean isSetVs() {
        return true;
    }

    /**
     * Gets the value of the ireg property.
     * 
     */
    public int getIreg() {
        return ireg;
    }

    /**
     * Sets the value of the ireg property.
     * 
     */
    public void setIreg(int value) {
        this.ireg = value;
    }

    public boolean isSetIreg() {
        return true;
    }

    /**
     * Gets the value of the zr property.
     * 
     */
    public double getZr() {
        return zr;
    }

    /**
     * Sets the value of the zr property.
     * 
     */
    public void setZr(double value) {
        this.zr = value;
    }

    public boolean isSetZr() {
        return true;
    }

    /**
     * Gets the value of the zx property.
     * 
     */
    public double getZx() {
        return zx;
    }

    /**
     * Sets the value of the zx property.
     * 
     */
    public void setZx(double value) {
        this.zx = value;
    }

    public boolean isSetZx() {
        return true;
    }

    /**
     * Gets the value of the rt property.
     * 
     */
    public double getRt() {
        return rt;
    }

    /**
     * Sets the value of the rt property.
     * 
     */
    public void setRt(double value) {
        this.rt = value;
    }

    public boolean isSetRt() {
        return true;
    }

    /**
     * Gets the value of the xt property.
     * 
     */
    public double getXt() {
        return xt;
    }

    /**
     * Sets the value of the xt property.
     * 
     */
    public void setXt(double value) {
        this.xt = value;
    }

    public boolean isSetXt() {
        return true;
    }

    /**
     * Gets the value of the gtap property.
     * 
     */
    public double getGtap() {
        return gtap;
    }

    /**
     * Sets the value of the gtap property.
     * 
     */
    public void setGtap(double value) {
        this.gtap = value;
    }

    public boolean isSetGtap() {
        return true;
    }

    /**
     * Gets the value of the rmPct property.
     * 
     */
    public double getRmPct() {
        return rmPct;
    }

    /**
     * Sets the value of the rmPct property.
     * 
     */
    public void setRmPct(double value) {
        this.rmPct = value;
    }

    public boolean isSetRmPct() {
        return true;
    }

    /**
     * Gets the value of the mrid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMrid() {
        return mrid;
    }

    /**
     * Sets the value of the mrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMrid(String value) {
        this.mrid = value;
    }

    public boolean isSetMrid() {
        return (this.mrid!= null);
    }

}
