//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.12 at 11:59:10 AM PDT 
//


package pnnl.goss.powergrid.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Transformer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Transformer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransformerId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PowergridId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BranchId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Ratio">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Icont">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TapPosition">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Angle">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Rma">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Rmi">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Vma">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Table1">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Transformer", propOrder = {
    "transformerId",
    "powergridId",
    "branchId",
    "ratio",
    "icont",
    "tapPosition",
    "angle",
    "rma",
    "rmi",
    "vma",
    "table1"
})
public class Transformer
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "TransformerId")
    protected int transformerId;
    @XmlElement(name = "PowergridId")
    protected int powergridId;
    @XmlElement(name = "BranchId")
    protected Integer branchId;
    @XmlElement(name = "Ratio")
    protected double ratio;
    @XmlElement(name = "Icont")
    protected int icont;
    @XmlElement(name = "TapPosition")
    protected double tapPosition;
    @XmlElement(name = "Angle")
    protected double angle;
    @XmlElement(name = "Rma")
    protected double rma;
    @XmlElement(name = "Rmi")
    protected double rmi;
    @XmlElement(name = "Vma")
    protected double vma;
    @XmlElement(name = "Table1", required = true)
    protected String table1;

    /**
     * Gets the value of the transformerId property.
     * 
     */
    public int getTransformerId() {
        return transformerId;
    }

    /**
     * Sets the value of the transformerId property.
     * 
     */
    public void setTransformerId(int value) {
        this.transformerId = value;
    }

    public boolean isSetTransformerId() {
        return true;
    }

    /**
     * Gets the value of the powergridId property.
     * 
     */
    public int getPowergridId() {
        return powergridId;
    }

    /**
     * Sets the value of the powergridId property.
     * 
     */
    public void setPowergridId(int value) {
        this.powergridId = value;
    }

    public boolean isSetPowergridId() {
        return true;
    }

    /**
     * Gets the value of the branchId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBranchId() {
        return branchId;
    }

    /**
     * Sets the value of the branchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBranchId(Integer value) {
        this.branchId = value;
    }

    public boolean isSetBranchId() {
        return (this.branchId!= null);
    }

    /**
     * Gets the value of the ratio property.
     * 
     */
    public double getRatio() {
        return ratio;
    }

    /**
     * Sets the value of the ratio property.
     * 
     */
    public void setRatio(double value) {
        this.ratio = value;
    }

    public boolean isSetRatio() {
        return true;
    }

    /**
     * Gets the value of the icont property.
     * 
     */
    public int getIcont() {
        return icont;
    }

    /**
     * Sets the value of the icont property.
     * 
     */
    public void setIcont(int value) {
        this.icont = value;
    }

    public boolean isSetIcont() {
        return true;
    }

    /**
     * Gets the value of the tapPosition property.
     * 
     */
    public double getTapPosition() {
        return tapPosition;
    }

    /**
     * Sets the value of the tapPosition property.
     * 
     */
    public void setTapPosition(double value) {
        this.tapPosition = value;
    }

    public boolean isSetTapPosition() {
        return true;
    }

    /**
     * Gets the value of the angle property.
     * 
     */
    public double getAngle() {
        return angle;
    }

    /**
     * Sets the value of the angle property.
     * 
     */
    public void setAngle(double value) {
        this.angle = value;
    }

    public boolean isSetAngle() {
        return true;
    }

    /**
     * Gets the value of the rma property.
     * 
     */
    public double getRma() {
        return rma;
    }

    /**
     * Sets the value of the rma property.
     * 
     */
    public void setRma(double value) {
        this.rma = value;
    }

    public boolean isSetRma() {
        return true;
    }

    /**
     * Gets the value of the rmi property.
     * 
     */
    public double getRmi() {
        return rmi;
    }

    /**
     * Sets the value of the rmi property.
     * 
     */
    public void setRmi(double value) {
        this.rmi = value;
    }

    public boolean isSetRmi() {
        return true;
    }

    /**
     * Gets the value of the vma property.
     * 
     */
    public double getVma() {
        return vma;
    }

    /**
     * Sets the value of the vma property.
     * 
     */
    public void setVma(double value) {
        this.vma = value;
    }

    public boolean isSetVma() {
        return true;
    }

    /**
     * Gets the value of the table1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTable1() {
        return table1;
    }

    /**
     * Sets the value of the table1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTable1(String value) {
        this.table1 = value;
    }

    public boolean isSetTable1() {
        return (this.table1 != null);
    }

}
