//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.12 at 11:59:10 AM PDT 
//


package pnnl.goss.powergrid.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for LoadTimeStep complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoadTimeStep">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LoadId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PowergridId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TimeStep">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Pload">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Qload">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoadTimeStep", propOrder = {
    "loadId",
    "powergridId",
    "timeStep",
    "pload",
    "qload"
})
public class LoadTimeStep
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "LoadId")
    protected int loadId;
    @XmlElement(name = "PowergridId")
    protected int powergridId;
    @XmlElement(name = "TimeStep", required = true)
    protected XMLGregorianCalendar timeStep;
    @XmlElement(name = "Pload")
    protected double pload;
    @XmlElement(name = "Qload")
    protected double qload;

    /**
     * Gets the value of the loadId property.
     * 
     */
    public int getLoadId() {
        return loadId;
    }

    /**
     * Sets the value of the loadId property.
     * 
     */
    public void setLoadId(int value) {
        this.loadId = value;
    }

    public boolean isSetLoadId() {
        return true;
    }

    /**
     * Gets the value of the powergridId property.
     * 
     */
    public int getPowergridId() {
        return powergridId;
    }

    /**
     * Sets the value of the powergridId property.
     * 
     */
    public void setPowergridId(int value) {
        this.powergridId = value;
    }

    public boolean isSetPowergridId() {
        return true;
    }

    /**
     * Gets the value of the timeStep property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStep() {
        return timeStep;
    }

    /**
     * Sets the value of the timeStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStep(XMLGregorianCalendar value) {
        this.timeStep = value;
    }

    public boolean isSetTimeStep() {
        return (this.timeStep!= null);
    }

    /**
     * Gets the value of the pload property.
     * 
     */
    public double getPload() {
        return pload;
    }

    /**
     * Sets the value of the pload property.
     * 
     */
    public void setPload(double value) {
        this.pload = value;
    }

    public boolean isSetPload() {
        return true;
    }

    /**
     * Gets the value of the qload property.
     * 
     */
    public double getQload() {
        return qload;
    }

    /**
     * Sets the value of the qload property.
     * 
     */
    public void setQload(double value) {
        this.qload = value;
    }

    public boolean isSetQload() {
        return true;
    }

}
