//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.12 at 11:59:10 AM PDT 
//


package pnnl.goss.powergrid.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MachineTimeStep complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MachineTimeStep">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MachineId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PowergridId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TimeStep">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Pgen">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Qgen">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Status">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MachineTimeStep", propOrder = {
    "machineId",
    "powergridId",
    "timeStep",
    "pgen",
    "qgen",
    "status"
})
public class MachineTimeStep
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "MachineId")
    protected int machineId;
    @XmlElement(name = "PowergridId")
    protected int powergridId;
    @XmlElement(name = "TimeStep", required = true)
    protected XMLGregorianCalendar timeStep;
    @XmlElement(name = "Pgen")
    protected double pgen;
    @XmlElement(name = "Qgen")
    protected double qgen;
    @XmlElement(name = "Status")
    protected int status;

    /**
     * Gets the value of the machineId property.
     * 
     */
    public int getMachineId() {
        return machineId;
    }

    /**
     * Sets the value of the machineId property.
     * 
     */
    public void setMachineId(int value) {
        this.machineId = value;
    }

    public boolean isSetMachineId() {
        return true;
    }

    /**
     * Gets the value of the powergridId property.
     * 
     */
    public int getPowergridId() {
        return powergridId;
    }

    /**
     * Sets the value of the powergridId property.
     * 
     */
    public void setPowergridId(int value) {
        this.powergridId = value;
    }

    public boolean isSetPowergridId() {
        return true;
    }

    /**
     * Gets the value of the timeStep property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStep() {
        return timeStep;
    }

    /**
     * Sets the value of the timeStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStep(XMLGregorianCalendar value) {
        this.timeStep = value;
    }

    public boolean isSetTimeStep() {
        return (this.timeStep!= null);
    }

    /**
     * Gets the value of the pgen property.
     * 
     */
    public double getPgen() {
        return pgen;
    }

    /**
     * Sets the value of the pgen property.
     * 
     */
    public void setPgen(double value) {
        this.pgen = value;
    }

    public boolean isSetPgen() {
        return true;
    }

    /**
     * Gets the value of the qgen property.
     * 
     */
    public double getQgen() {
        return qgen;
    }

    /**
     * Sets the value of the qgen property.
     * 
     */
    public void setQgen(double value) {
        this.qgen = value;
    }

    public boolean isSetQgen() {
        return true;
    }

    /**
     * Gets the value of the status property.
     * 
     */
    public int getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     */
    public void setStatus(int value) {
        this.status = value;
    }

    public boolean isSetStatus() {
        return true;
    }

}
