//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.12 at 11:59:10 AM PDT 
//


package pnnl.goss.powergrid.datamodel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pnnl.goss.powergrid.datamodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pnnl.goss.powergrid.datamodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Area }
     * 
     */
    public Area createArea() {
        return new Area();
    }

    /**
     * Create an instance of {@link BusTimestep }
     * 
     */
    public BusTimestep createBusTimestep() {
        return new BusTimestep();
    }

    /**
     * Create an instance of {@link EquipmentContainer }
     * 
     */
    public EquipmentContainer createEquipmentContainer() {
        return new EquipmentContainer();
    }

    /**
     * Create an instance of {@link Transformer }
     * 
     */
    public Transformer createTransformer() {
        return new Transformer();
    }

    /**
     * Create an instance of {@link TerminalSwitchMap }
     * 
     */
    public TerminalSwitchMap createTerminalSwitchMap() {
        return new TerminalSwitchMap();
    }

    /**
     * Create an instance of {@link Terminal }
     * 
     */
    public Terminal createTerminal() {
        return new Terminal();
    }

    /**
     * Create an instance of {@link Zbr }
     * 
     */
    public Zbr createZbr() {
        return new Zbr();
    }

    /**
     * Create an instance of {@link TerminalBranchlMap }
     * 
     */
    public TerminalBranchlMap createTerminalBranchlMap() {
        return new TerminalBranchlMap();
    }

    /**
     * Create an instance of {@link SwitchedShunt }
     * 
     */
    public SwitchedShunt createSwitchedShunt() {
        return new SwitchedShunt();
    }

    /**
     * Create an instance of {@link Powergrid }
     * 
     */
    public Powergrid createPowergrid() {
        return new Powergrid();
    }

    /**
     * Create an instance of {@link ContingencyTimeStep }
     * 
     */
    public ContingencyTimeStep createContingencyTimeStep() {
        return new ContingencyTimeStep();
    }

    /**
     * Create an instance of {@link ContingencyBranchOut }
     * 
     */
    public ContingencyBranchOut createContingencyBranchOut() {
        return new ContingencyBranchOut();
    }

    /**
     * Create an instance of {@link ContingencyBusViolation }
     * 
     */
    public ContingencyBusViolation createContingencyBusViolation() {
        return new ContingencyBusViolation();
    }

    /**
     * Create an instance of {@link TerminalZbrmap }
     * 
     */
    public TerminalZbrmap createTerminalZbrmap() {
        return new TerminalZbrmap();
    }

    /**
     * Create an instance of {@link Contingency }
     * 
     */
    public Contingency createContingency() {
        return new Contingency();
    }

    /**
     * Create an instance of {@link PowergridTimeStep }
     * 
     */
    public PowergridTimeStep createPowergridTimeStep() {
        return new PowergridTimeStep();
    }

    /**
     * Create an instance of {@link LoadTimeStep }
     * 
     */
    public LoadTimeStep createLoadTimeStep() {
        return new LoadTimeStep();
    }

    /**
     * Create an instance of {@link Substation }
     * 
     */
    public Substation createSubstation() {
        return new Substation();
    }

    /**
     * Create an instance of {@link Machine }
     * 
     */
    public Machine createMachine() {
        return new Machine();
    }

    /**
     * Create an instance of {@link Bus }
     * 
     */
    public Bus createBus() {
        return new Bus();
    }

    /**
     * Create an instance of {@link Line }
     * 
     */
    public Line createLine() {
        return new Line();
    }

    /**
     * Create an instance of {@link Load }
     * 
     */
    public Load createLoad() {
        return new Load();
    }

    /**
     * Create an instance of {@link MachineTimeStep }
     * 
     */
    public MachineTimeStep createMachineTimeStep() {
        return new MachineTimeStep();
    }

    /**
     * Create an instance of {@link ConnectivityNode }
     * 
     */
    public ConnectivityNode createConnectivityNode() {
        return new ConnectivityNode();
    }

    /**
     * Create an instance of {@link GlobalMrid }
     * 
     */
    public GlobalMrid createGlobalMrid() {
        return new GlobalMrid();
    }

    /**
     * Create an instance of {@link Switch }
     * 
     */
    public Switch createSwitch() {
        return new Switch();
    }

    /**
     * Create an instance of {@link TransformerTimeStep }
     * 
     */
    public TransformerTimeStep createTransformerTimeStep() {
        return new TransformerTimeStep();
    }

    /**
     * Create an instance of {@link LineTimeStep }
     * 
     */
    public LineTimeStep createLineTimeStep() {
        return new LineTimeStep();
    }

    /**
     * Create an instance of {@link Branch }
     * 
     */
    public Branch createBranch() {
        return new Branch();
    }

    /**
     * Create an instance of {@link Measurement }
     * 
     */
    public Measurement createMeasurement() {
        return new Measurement();
    }

    /**
     * Create an instance of {@link SwitchedShuntTimeStep }
     * 
     */
    public SwitchedShuntTimeStep createSwitchedShuntTimeStep() {
        return new SwitchedShuntTimeStep();
    }

    /**
     * Create an instance of {@link Zone }
     * 
     */
    public Zone createZone() {
        return new Zone();
    }

    /**
     * Create an instance of {@link ContingencyBranchViolationTimeStep }
     * 
     */
    public ContingencyBranchViolationTimeStep createContingencyBranchViolationTimeStep() {
        return new ContingencyBranchViolationTimeStep();
    }

    /**
     * Create an instance of {@link ContingencyBranchViolation }
     * 
     */
    public ContingencyBranchViolation createContingencyBranchViolation() {
        return new ContingencyBranchViolation();
    }

    /**
     * Create an instance of {@link ContingencyBusViolationTimeStep }
     * 
     */
    public ContingencyBusViolationTimeStep createContingencyBusViolationTimeStep() {
        return new ContingencyBusViolationTimeStep();
    }

}
