<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sp" nsURI="http://goss.pnnl.gov/sp" nsPrefix="gov.pnnl.goss.sp">
  <eClassifiers xsi:type="ecore:EClass" name="ACLineSegment" eSuperTypes="http://goss.pnnl.gov/common#//IdentifiedObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="org.eclipse.emf.texo">
        <details key="java.member" value="status"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kvlevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="org.eclipse.emf.texo">
        <details key="java.member" value="kvlevel"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rating" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="org.eclipse.emf.texo">
        <details key="java.member" value="rating"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="substations" upperBound="-1"
        eType="#//Substation">
      <eAnnotations source="org.eclipse.emf.texo">
        <details key="java.member" value="substations"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mvaFlow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="org.eclipse.emf.texo">
        <details key="java.member" value="mvaFlow"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Region" eSuperTypes="http://goss.pnnl.gov/common#//IdentifiedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="substations" upperBound="-1"
        eType="#//Substation">
      <eAnnotations source="org.eclipse.emf.texo">
        <details key="java.member" value="substations"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="organization" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="org.eclipse.emf.texo">
        <details key="java.member" value="organization"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location" eSuperTypes="http://goss.pnnl.gov/common#//IdentifiedObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latitude" eType="#//Latitude">
      <eAnnotations source="org.eclipse.emf.texo">
        <details key="java.member" value="latitude"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitude" eType="#//Longitude">
      <eAnnotations source="org.eclipse.emf.texo">
        <details key="java.member" value="longitude"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Substation" eSuperTypes="http://goss.pnnl.gov/common#//IdentifiedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="#//Location">
      <eAnnotations source="org.eclipse.emf.texo">
        <details key="java.member" value="location"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="regionMRID" eType="ecore:EDataType http://goss.pnnl.gov/common#//MRID">
      <eAnnotations source="org.eclipse.emf.texo">
        <details key="java.member" value="regionMRID"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="regionName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="org.eclipse.emf.texo">
        <details key="java.member" value="regionName"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Latitude" instanceClassName="java.lang.Double"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Longitude" instanceClassName="java.lang.Double"/>
</ecore:EPackage>
